3 1 templates
thinknetica-django-lab-01/Nazira17 pull request #30
Opened 2021-01-29 11:01 UTC by Nazira17

Closes #21

2021-01-29 11:07 UTC, mikhailborodin requested changes

2021-01-29 11:07 UTC, mikhailborodin commented on django_project/django_project/templates/pages/index.html
> +{% include 'new.html' with user=customers%}
так у вас тэг header получится ниже контента страницы а block header внутри файла new.html и содержит только одну строку. Вы проверили, что у вас верстка нормально отображается?

2021-01-29 14:57 UTC, Nazira17 commented on django_project/django_project/templates/pages/index.html
> +{% include 'new.html' with user=customers%}
![Снимок экрана от 2021-01-29 20-48-24](https://user-images.githubusercontent.com/45563010/106290330-8b6f7d00-6274-11eb-99d7-b43f6a10b534.png)

добавила

2021-01-30 06:21 UTC, mikhailborodin approved these changes

2021-01-30 15:32 UTC, merged