7_1
thinknetica-django-lab-01/Nazira17 pull request #71
Opened 2021-02-18 10:59 UTC by Nazira17

Closes #53 
![Снимок экрана от 2021-02-18 16-48-29](https://user-images.githubusercontent.com/45563010/108347306-903ba700-720a-11eb-9a23-849f31d41476.png)

2021-02-19 06:01 UTC, mikhailborodin requested changes

2021-02-19 06:01 UTC, mikhailborodin commented on django_project/django_project/settings.py
у вас в скриншоте показано, что celery не может подключиться к брокеру. Исправьте CELERY_BROKER_URL

2021-02-20 11:41 UTC, Nazira17 commented on django_project/django_project/settings.py
исправила, результаты сохраняются и отображаются в админке.
![Снимок экрана от 2021-02-20 17-39-29](https://user-images.githubusercontent.com/45563010/108594208-b8f6a480-73a2-11eb-9fef-abb5ea506c48.png)

2021-02-21 08:40 UTC, mikhailborodin approved these changes

2021-02-23 05:18 UTC, merged