Add cache redis django
thinknetica-django-lab-01/Nazira17 pull request #80
Opened 2021-02-26 13:15 UTC by Nazira17

Closes #49 
![Снимок экрана от 2021-02-26 19-10-19](https://user-images.githubusercontent.com/45563010/109304827-040f2c80-7867-11eb-8e79-3819fe70ecea.png)

2021-02-26 16:52 UTC, mikhailborodin requested changes

2021-02-26 16:52 UTC, mikhailborodin commented on django_project/main/tasks.py
> +@cache_page(CACHE_TTL)
отклоняю пул реквест

2021-02-28 04:21 UTC, Nazira17 commented on django_project/main/tasks.py
> +@cache_page(CACHE_TTL)
исправила.

2021-02-28 09:19 UTC, mikhailborodin requested changes

2021-02-28 09:19 UTC, mikhailborodin commented on django_project/main/views.py
> +@cache_page(CACHE_TTL)
просто добавление декоратора cache_page на класс не добавит кэширование представлений https://stackoverflow.com/questions/21293543/cache-page-with-class-based-views

2021-03-02 06:39 UTC, mikhailborodin approved these changes

2021-03-02 08:22 UTC, merged